### PR TITLE
Attempt to fix a problem?

### LINKED ISSUE #14: Freeze_support() error
Hi I keep getting this error:

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

### PR DESCRIPTION
**Pull request by buthed010203**
This should close #14 I think? I'm not quite sure and don't get that error myself of windows so I can't really test.

### CODE REVIEW

**Comment by NotSoNooby** [comment]
this fix works, except im being spammed with OSError: [Errno 48] Address already in use.

**Comment by buthed010203** [comment]
> OSError: [Errno 48] Address already in use.

@NotSoNooby AFAIK thats related to flask already being started on that port, try rebooting your computer maybe? Idk

**Comment by kevinjycui** [comment]
@NotSoNooby The address error is probably an issue where you have something else already running on that port. You can try changing the port in the front end and back end or rebooting as @buthed010203 suggested. Nonetheless, it's probably irrelevant to this PR so I'll just merge it

**Comment by NotSoNooby** [comment]
rebooting didn't work. how would i change the ports?

**Comment by NotSoNooby** [comment]
ok i managed to fix this by puting it under a "if __name__ == "__main__""

**Pull request merged**
